### ISSUE TITLE
Repo structure

### ISSUE THREAD

**Issue by 0oM4R** [0oM4R/node101#1]
Create repo structure

**Comment by fatma-taysir** [comment]
├── node_modules/
├── src/
│   ├── index.js
│   ├── controllers/
│   │   ├── userController.js
│   │   └── ...
│   ├── models/
│   │   ├── userModel.js
│   │   └── ...
│   ├── routes/
│   │   ├── userRoutes.js
│   │   └── ...
│   ├── services/
│   │   ├── userService.js
│   │   └── ...
│   └── utils/
│       ├── errorHandlers.js
│       └── ...
├── tests/
│   ├── controllers/
│   ├── models/
│   ├── routes/
│   └── services/
├── .env
├── .gitignore
├── package.json
├── package-lock.json
└── README.md

**Comment by 0oM4R** [comment]
https://blog.risingstack.com/node-hero-node-js-project-structure-tutorial/
